#ifndef ROBOTVIEWER_IDL
#define ROBOTVIEWER_IDL

module hpp {
  typedef sequence<double> DoubleSeq;
  typedef sequence<string> ElementList;

  interface RobotViewer
  {
    exception InvalidKey{
      string reason;
    };

    boolean createElement(in string type, in string name, in string description);

    boolean destroyElement(in string name) raises(InvalidKey);
    boolean enableElement(in string name) raises(InvalidKey) ;
    boolean disableElement(in string name) raises(InvalidKey) ;
    boolean updateElementConfig(in string name, in DoubleSeq config) raises(InvalidKey);
    void getElementConfig(in string name, out DoubleSeq config) raises(InvalidKey);

    void listElement(out ElementList list);
    void Ping(out string outstring);
  };
};
#endif