# Python stubs generated by omniidl from RobotViewer.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "robotviewer_corba"
#
__name__ = "robotviewer_corba"
_0_robotviewer_corba = omniORB.openModule("robotviewer_corba", r"RobotViewer.idl")
_0_robotviewer_corba__POA = omniORB.openModule("robotviewer_corba__POA", r"RobotViewer.idl")


# typedef ... DoubleSeq
class DoubleSeq:
    _NP_RepositoryId = "IDL:robotviewer_corba/DoubleSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_robotviewer_corba.DoubleSeq = DoubleSeq
_0_robotviewer_corba._d_DoubleSeq  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 0)
_0_robotviewer_corba._ad_DoubleSeq = (omniORB.tcInternal.tv_alias, DoubleSeq._NP_RepositoryId, "DoubleSeq", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 0))
_0_robotviewer_corba._tc_DoubleSeq = omniORB.tcInternal.createTypeCode(_0_robotviewer_corba._ad_DoubleSeq)
omniORB.registerType(DoubleSeq._NP_RepositoryId, _0_robotviewer_corba._ad_DoubleSeq, _0_robotviewer_corba._tc_DoubleSeq)
del DoubleSeq

# typedef ... ElementList
class ElementList:
    _NP_RepositoryId = "IDL:robotviewer_corba/ElementList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_robotviewer_corba.ElementList = ElementList
_0_robotviewer_corba._d_ElementList  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_robotviewer_corba._ad_ElementList = (omniORB.tcInternal.tv_alias, ElementList._NP_RepositoryId, "ElementList", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_robotviewer_corba._tc_ElementList = omniORB.tcInternal.createTypeCode(_0_robotviewer_corba._ad_ElementList)
omniORB.registerType(ElementList._NP_RepositoryId, _0_robotviewer_corba._ad_ElementList, _0_robotviewer_corba._tc_ElementList)
del ElementList

# interface RobotViewer
_0_robotviewer_corba._d_RobotViewer = (omniORB.tcInternal.tv_objref, "IDL:robotviewer_corba/RobotViewer:1.0", "RobotViewer")
omniORB.typeMapping["IDL:robotviewer_corba/RobotViewer:1.0"] = _0_robotviewer_corba._d_RobotViewer
_0_robotviewer_corba.RobotViewer = omniORB.newEmptyClass()
class RobotViewer :
    _NP_RepositoryId = _0_robotviewer_corba._d_RobotViewer[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil

    
    # exception InvalidKey
    _0_robotviewer_corba.RobotViewer.InvalidKey = omniORB.newEmptyClass()
    class InvalidKey (CORBA.UserException):
        _NP_RepositoryId = "IDL:robotviewer_corba/RobotViewer/InvalidKey:1.0"

        _NP_ClassName = "robotviewer_corba.RobotViewer.InvalidKey"

        def __init__(self, reason):
            CORBA.UserException.__init__(self, reason)
            self.reason = reason
    
    _d_InvalidKey  = (omniORB.tcInternal.tv_except, InvalidKey, InvalidKey._NP_RepositoryId, "InvalidKey", "reason", (omniORB.tcInternal.tv_string,0))
    _tc_InvalidKey = omniORB.tcInternal.createTypeCode(_d_InvalidKey)
    omniORB.registerType(InvalidKey._NP_RepositoryId, _d_InvalidKey, _tc_InvalidKey)


_0_robotviewer_corba.RobotViewer = RobotViewer
_0_robotviewer_corba._tc_RobotViewer = omniORB.tcInternal.createTypeCode(_0_robotviewer_corba._d_RobotViewer)
omniORB.registerType(RobotViewer._NP_RepositoryId, _0_robotviewer_corba._d_RobotViewer, _0_robotviewer_corba._tc_RobotViewer)

# RobotViewer operations and attributes
RobotViewer._d_createElement = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
RobotViewer._d_setRobotJointRank = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
RobotViewer._d_destroyElement = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), {_0_robotviewer_corba.RobotViewer.InvalidKey._NP_RepositoryId: _0_robotviewer_corba.RobotViewer._d_InvalidKey})
RobotViewer._d_enableElement = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), {_0_robotviewer_corba.RobotViewer.InvalidKey._NP_RepositoryId: _0_robotviewer_corba.RobotViewer._d_InvalidKey})
RobotViewer._d_disableElement = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), {_0_robotviewer_corba.RobotViewer.InvalidKey._NP_RepositoryId: _0_robotviewer_corba.RobotViewer._d_InvalidKey})
RobotViewer._d_updateElementConfig = (((omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:robotviewer_corba/DoubleSeq:1.0"]), (omniORB.tcInternal.tv_boolean, ), {_0_robotviewer_corba.RobotViewer.InvalidKey._NP_RepositoryId: _0_robotviewer_corba.RobotViewer._d_InvalidKey})
RobotViewer._d_getElementConfig = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:robotviewer_corba/DoubleSeq:1.0"], ), {_0_robotviewer_corba.RobotViewer.InvalidKey._NP_RepositoryId: _0_robotviewer_corba.RobotViewer._d_InvalidKey})
RobotViewer._d_listElements = ((), (omniORB.typeMapping["IDL:robotviewer_corba/ElementList:1.0"], ), None)
RobotViewer._d_listElementDofs = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:robotviewer_corba/ElementList:1.0"], ), None)
RobotViewer._d_listMeshes = ((), (omniORB.typeMapping["IDL:robotviewer_corba/ElementList:1.0"], ), None)
RobotViewer._d_getGlConfig = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:robotviewer_corba/DoubleSeq:1.0"], ), {_0_robotviewer_corba.RobotViewer.InvalidKey._NP_RepositoryId: _0_robotviewer_corba.RobotViewer._d_InvalidKey})
RobotViewer._d_Ping = ((), ((omniORB.tcInternal.tv_string,0), ), None)

# RobotViewer object reference
class _objref_RobotViewer (CORBA.Object):
    _NP_RepositoryId = RobotViewer._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def createElement(self, *args):
        return _omnipy.invoke(self, "createElement", _0_robotviewer_corba.RobotViewer._d_createElement, args)

    def setRobotJointRank(self, *args):
        return _omnipy.invoke(self, "setRobotJointRank", _0_robotviewer_corba.RobotViewer._d_setRobotJointRank, args)

    def destroyElement(self, *args):
        return _omnipy.invoke(self, "destroyElement", _0_robotviewer_corba.RobotViewer._d_destroyElement, args)

    def enableElement(self, *args):
        return _omnipy.invoke(self, "enableElement", _0_robotviewer_corba.RobotViewer._d_enableElement, args)

    def disableElement(self, *args):
        return _omnipy.invoke(self, "disableElement", _0_robotviewer_corba.RobotViewer._d_disableElement, args)

    def updateElementConfig(self, *args):
        return _omnipy.invoke(self, "updateElementConfig", _0_robotviewer_corba.RobotViewer._d_updateElementConfig, args)

    def getElementConfig(self, *args):
        return _omnipy.invoke(self, "getElementConfig", _0_robotviewer_corba.RobotViewer._d_getElementConfig, args)

    def listElements(self, *args):
        return _omnipy.invoke(self, "listElements", _0_robotviewer_corba.RobotViewer._d_listElements, args)

    def listElementDofs(self, *args):
        return _omnipy.invoke(self, "listElementDofs", _0_robotviewer_corba.RobotViewer._d_listElementDofs, args)

    def listMeshes(self, *args):
        return _omnipy.invoke(self, "listMeshes", _0_robotviewer_corba.RobotViewer._d_listMeshes, args)

    def getGlConfig(self, *args):
        return _omnipy.invoke(self, "getGlConfig", _0_robotviewer_corba.RobotViewer._d_getGlConfig, args)

    def Ping(self, *args):
        return _omnipy.invoke(self, "Ping", _0_robotviewer_corba.RobotViewer._d_Ping, args)

    __methods__ = ["createElement", "setRobotJointRank", "destroyElement", "enableElement", "disableElement", "updateElementConfig", "getElementConfig", "listElements", "listElementDofs", "listMeshes", "getGlConfig", "Ping"] + CORBA.Object.__methods__

omniORB.registerObjref(RobotViewer._NP_RepositoryId, _objref_RobotViewer)
_0_robotviewer_corba._objref_RobotViewer = _objref_RobotViewer
del RobotViewer, _objref_RobotViewer

# RobotViewer skeleton
__name__ = "robotviewer_corba__POA"
class RobotViewer (PortableServer.Servant):
    _NP_RepositoryId = _0_robotviewer_corba.RobotViewer._NP_RepositoryId


    _omni_op_d = {"createElement": _0_robotviewer_corba.RobotViewer._d_createElement, "setRobotJointRank": _0_robotviewer_corba.RobotViewer._d_setRobotJointRank, "destroyElement": _0_robotviewer_corba.RobotViewer._d_destroyElement, "enableElement": _0_robotviewer_corba.RobotViewer._d_enableElement, "disableElement": _0_robotviewer_corba.RobotViewer._d_disableElement, "updateElementConfig": _0_robotviewer_corba.RobotViewer._d_updateElementConfig, "getElementConfig": _0_robotviewer_corba.RobotViewer._d_getElementConfig, "listElements": _0_robotviewer_corba.RobotViewer._d_listElements, "listElementDofs": _0_robotviewer_corba.RobotViewer._d_listElementDofs, "listMeshes": _0_robotviewer_corba.RobotViewer._d_listMeshes, "getGlConfig": _0_robotviewer_corba.RobotViewer._d_getGlConfig, "Ping": _0_robotviewer_corba.RobotViewer._d_Ping}

RobotViewer._omni_skeleton = RobotViewer
_0_robotviewer_corba__POA.RobotViewer = RobotViewer
omniORB.registerSkeleton(RobotViewer._NP_RepositoryId, RobotViewer)
del RobotViewer
__name__ = "robotviewer_corba"

#
# End of module "robotviewer_corba"
#
__name__ = "RobotViewer_idl"

_exported_modules = ( "robotviewer_corba", )

# The end.
