# DO NOT EDIT THIS FILE!
#
# Python module robotviewer_corba generated by omniidl

import omniORB
omniORB.updateModule("robotviewer_corba")

# ** 1. Stub files contributing to this module
import RobotViewer_idl

# ** 2. Sub-modules

# ** 3. End
