# DO NOT EDIT THIS FILE!
#
# Python module hpp generated by omniidl

import omniORB
omniORB.updateModule("hpp")

# ** 1. Stub files contributing to this module
import RobotViewer_idl

# ** 2. Sub-modules

# ** 3. End
