# DO NOT EDIT THIS FILE!
#
# Python module hppCorbaServer__POA generated by omniidl

import omniORB
omniORB.updateModule("hppCorbaServer__POA")

# ** 1. Stub files contributing to this module
import sot_idl

# ** 2. Sub-modules

# ** 3. End
