# Python stubs generated by omniidl from sot.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "hppCorbaServer"
#
__name__ = "hppCorbaServer"
_0_hppCorbaServer = omniORB.openModule("hppCorbaServer", r"sot.idl")
_0_hppCorbaServer__POA = omniORB.openModule("hppCorbaServer__POA", r"sot.idl")


# typedef ... DoubleSeq
class DoubleSeq:
    _NP_RepositoryId = "IDL:hppCorbaServer/DoubleSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_hppCorbaServer.DoubleSeq = DoubleSeq
_0_hppCorbaServer._d_DoubleSeq  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 0)
_0_hppCorbaServer._ad_DoubleSeq = (omniORB.tcInternal.tv_alias, DoubleSeq._NP_RepositoryId, "DoubleSeq", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_double, 0))
_0_hppCorbaServer._tc_DoubleSeq = omniORB.tcInternal.createTypeCode(_0_hppCorbaServer._ad_DoubleSeq)
omniORB.registerType(DoubleSeq._NP_RepositoryId, _0_hppCorbaServer._ad_DoubleSeq, _0_hppCorbaServer._tc_DoubleSeq)
del DoubleSeq

# typedef ... StringStreamer
class StringStreamer:
    _NP_RepositoryId = "IDL:hppCorbaServer/StringStreamer:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_hppCorbaServer.StringStreamer = StringStreamer
_0_hppCorbaServer._d_StringStreamer  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_char, 0)
_0_hppCorbaServer._ad_StringStreamer = (omniORB.tcInternal.tv_alias, StringStreamer._NP_RepositoryId, "StringStreamer", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_char, 0))
_0_hppCorbaServer._tc_StringStreamer = omniORB.tcInternal.createTypeCode(_0_hppCorbaServer._ad_StringStreamer)
omniORB.registerType(StringStreamer._NP_RepositoryId, _0_hppCorbaServer._ad_StringStreamer, _0_hppCorbaServer._tc_StringStreamer)
del StringStreamer

# interface NotifyCallback
_0_hppCorbaServer._d_NotifyCallback = (omniORB.tcInternal.tv_objref, "IDL:hppCorbaServer/NotifyCallback:1.0", "NotifyCallback")
omniORB.typeMapping["IDL:hppCorbaServer/NotifyCallback:1.0"] = _0_hppCorbaServer._d_NotifyCallback
_0_hppCorbaServer.NotifyCallback = omniORB.newEmptyClass()
class NotifyCallback :
    _NP_RepositoryId = _0_hppCorbaServer._d_NotifyCallback[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_hppCorbaServer.NotifyCallback = NotifyCallback
_0_hppCorbaServer._tc_NotifyCallback = omniORB.tcInternal.createTypeCode(_0_hppCorbaServer._d_NotifyCallback)
omniORB.registerType(NotifyCallback._NP_RepositoryId, _0_hppCorbaServer._d_NotifyCallback, _0_hppCorbaServer._tc_NotifyCallback)

# NotifyCallback operations and attributes
NotifyCallback._d_notifyClient = ((), (), None)

# NotifyCallback object reference
class _objref_NotifyCallback (CORBA.Object):
    _NP_RepositoryId = NotifyCallback._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def notifyClient(self, *args):
        return _omnipy.invoke(self, "notifyClient", _0_hppCorbaServer.NotifyCallback._d_notifyClient, args)

    __methods__ = ["notifyClient"] + CORBA.Object.__methods__

omniORB.registerObjref(NotifyCallback._NP_RepositoryId, _objref_NotifyCallback)
_0_hppCorbaServer._objref_NotifyCallback = _objref_NotifyCallback
del NotifyCallback, _objref_NotifyCallback

# NotifyCallback skeleton
__name__ = "hppCorbaServer__POA"
class NotifyCallback (PortableServer.Servant):
    _NP_RepositoryId = _0_hppCorbaServer.NotifyCallback._NP_RepositoryId


    _omni_op_d = {"notifyClient": _0_hppCorbaServer.NotifyCallback._d_notifyClient}

NotifyCallback._omni_skeleton = NotifyCallback
_0_hppCorbaServer__POA.NotifyCallback = NotifyCallback
omniORB.registerSkeleton(NotifyCallback._NP_RepositoryId, NotifyCallback)
del NotifyCallback
__name__ = "hppCorbaServer"

# interface SOT_Server_Command
_0_hppCorbaServer._d_SOT_Server_Command = (omniORB.tcInternal.tv_objref, "IDL:hppCorbaServer/SOT_Server_Command:1.0", "SOT_Server_Command")
omniORB.typeMapping["IDL:hppCorbaServer/SOT_Server_Command:1.0"] = _0_hppCorbaServer._d_SOT_Server_Command
_0_hppCorbaServer.SOT_Server_Command = omniORB.newEmptyClass()
class SOT_Server_Command :
    _NP_RepositoryId = _0_hppCorbaServer._d_SOT_Server_Command[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_hppCorbaServer.SOT_Server_Command = SOT_Server_Command
_0_hppCorbaServer._tc_SOT_Server_Command = omniORB.tcInternal.createTypeCode(_0_hppCorbaServer._d_SOT_Server_Command)
omniORB.registerType(SOT_Server_Command._NP_RepositoryId, _0_hppCorbaServer._d_SOT_Server_Command, _0_hppCorbaServer._tc_SOT_Server_Command)

# SOT_Server_Command operations and attributes
SOT_Server_Command._d_run = (((omniORB.tcInternal.tv_string,0), ), (), None)
SOT_Server_Command._d_runAndRead = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:hppCorbaServer/StringStreamer:1.0"], ), None)
SOT_Server_Command._d_readVector = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:hppCorbaServer/DoubleSeq:1.0"], ), None)
SOT_Server_Command._d_createOutputVectorSignal = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_long, ), None)
SOT_Server_Command._d_createInputVectorSignal = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_long, ), None)
SOT_Server_Command._d_readInputVectorSignal = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:hppCorbaServer/DoubleSeq:1.0"], ), None)
SOT_Server_Command._d_writeOutputVectorSignal = ((omniORB.tcInternal.tv_long, omniORB.typeMapping["IDL:hppCorbaServer/DoubleSeq:1.0"]), (), None)
SOT_Server_Command._d_registerClient = ((omniORB.typeMapping["IDL:hppCorbaServer/NotifyCallback:1.0"], (omniORB.tcInternal.tv_string,0)), (), None)
SOT_Server_Command._d_unregisterClient = (((omniORB.tcInternal.tv_string,0), ), (), None)

# SOT_Server_Command object reference
class _objref_SOT_Server_Command (CORBA.Object):
    _NP_RepositoryId = SOT_Server_Command._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def run(self, *args):
        return _omnipy.invoke(self, "run", _0_hppCorbaServer.SOT_Server_Command._d_run, args)

    def runAndRead(self, *args):
        return _omnipy.invoke(self, "runAndRead", _0_hppCorbaServer.SOT_Server_Command._d_runAndRead, args)

    def readVector(self, *args):
        return _omnipy.invoke(self, "readVector", _0_hppCorbaServer.SOT_Server_Command._d_readVector, args)

    def createOutputVectorSignal(self, *args):
        return _omnipy.invoke(self, "createOutputVectorSignal", _0_hppCorbaServer.SOT_Server_Command._d_createOutputVectorSignal, args)

    def createInputVectorSignal(self, *args):
        return _omnipy.invoke(self, "createInputVectorSignal", _0_hppCorbaServer.SOT_Server_Command._d_createInputVectorSignal, args)

    def readInputVectorSignal(self, *args):
        return _omnipy.invoke(self, "readInputVectorSignal", _0_hppCorbaServer.SOT_Server_Command._d_readInputVectorSignal, args)

    def writeOutputVectorSignal(self, *args):
        return _omnipy.invoke(self, "writeOutputVectorSignal", _0_hppCorbaServer.SOT_Server_Command._d_writeOutputVectorSignal, args)

    def registerClient(self, *args):
        return _omnipy.invoke(self, "registerClient", _0_hppCorbaServer.SOT_Server_Command._d_registerClient, args)

    def unregisterClient(self, *args):
        return _omnipy.invoke(self, "unregisterClient", _0_hppCorbaServer.SOT_Server_Command._d_unregisterClient, args)

    __methods__ = ["run", "runAndRead", "readVector", "createOutputVectorSignal", "createInputVectorSignal", "readInputVectorSignal", "writeOutputVectorSignal", "registerClient", "unregisterClient"] + CORBA.Object.__methods__

omniORB.registerObjref(SOT_Server_Command._NP_RepositoryId, _objref_SOT_Server_Command)
_0_hppCorbaServer._objref_SOT_Server_Command = _objref_SOT_Server_Command
del SOT_Server_Command, _objref_SOT_Server_Command

# SOT_Server_Command skeleton
__name__ = "hppCorbaServer__POA"
class SOT_Server_Command (PortableServer.Servant):
    _NP_RepositoryId = _0_hppCorbaServer.SOT_Server_Command._NP_RepositoryId


    _omni_op_d = {"run": _0_hppCorbaServer.SOT_Server_Command._d_run, "runAndRead": _0_hppCorbaServer.SOT_Server_Command._d_runAndRead, "readVector": _0_hppCorbaServer.SOT_Server_Command._d_readVector, "createOutputVectorSignal": _0_hppCorbaServer.SOT_Server_Command._d_createOutputVectorSignal, "createInputVectorSignal": _0_hppCorbaServer.SOT_Server_Command._d_createInputVectorSignal, "readInputVectorSignal": _0_hppCorbaServer.SOT_Server_Command._d_readInputVectorSignal, "writeOutputVectorSignal": _0_hppCorbaServer.SOT_Server_Command._d_writeOutputVectorSignal, "registerClient": _0_hppCorbaServer.SOT_Server_Command._d_registerClient, "unregisterClient": _0_hppCorbaServer.SOT_Server_Command._d_unregisterClient}

SOT_Server_Command._omni_skeleton = SOT_Server_Command
_0_hppCorbaServer__POA.SOT_Server_Command = SOT_Server_Command
omniORB.registerSkeleton(SOT_Server_Command._NP_RepositoryId, SOT_Server_Command)
del SOT_Server_Command
__name__ = "hppCorbaServer"

#
# End of module "hppCorbaServer"
#
__name__ = "sot_idl"

_exported_modules = ( "hppCorbaServer", )

# The end.
