# DO NOT EDIT THIS FILE!
#
# Python module RobotViewer__POA generated by omniidl

import omniORB
omniORB.updateModule("RobotViewer__POA")

# ** 1. Stub files contributing to this module
import RobotViewer_idl

# ** 2. Sub-modules

# ** 3. End
